### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kssrao13882** [Octavi-Staging/maintainership#1]
## Device you want to apply for
```
Realme 5 Pro - RMX1971 
```

## Device tree sources

```
https://github.com/kssrao13882/device_realme_RMX1971-A13
 
https://github.com/kssrao13882/device_realme_sdm710-common_A13
 
https://gitlab.com/kssrao13882/kernel_realme_sdm710
 https://gitlab.com/kssrao13882/vendor_realme_RMX1971
 
https://gitlab.com/kssrao13882/vendor_realme_sdm710-common
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Realme5Pro_Downloads/1818
```

## Other ROM's you maintain officially or unofficially
```
riceDroid, Project Xtended, Spark
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1.5 Years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact

```
@kssrao13882
```

**Comment by rockstar5495** [comment]
trees looks fine. Welcome to team will add to group soon.

**Comment by kssrao13882** [comment]
> trees looks fine. Welcome to team will add to group soon.

Thanks a lot. Looking forward for a long association with the team
