### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by TejasKamat** [Octavi-Staging/maintainership#11]
## Redmi Note 10 (mojito)
```
Redmi note 10 (mojito)
```

## Device tree sources
```
https://github.com/TejasKamat/device_xiaomi_mojito
https://github.com/TejasKamat/vendor_xiaomi_mojito
https://github.com/TejasKamat/kernel_xiaomi_mojito
```

## Link to the platform where you have released your unofficial build
```
https://github.com/TejasKamat/mojito_releases/releases/tag/v4.2-26032023
```

## Other ROM's you maintain officially or unofficially
```
EvolutionX unofficially, [Here](https://t.me/RN10channel/1314)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 years
```

## SELinux status?
```
Enforcing!
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@TejasKamat
```

**Comment by beingmishra** [comment]
Rejecting as the applied user is banned from Octavi
