### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by jaymistry258** [Octavi-Staging/maintainership#16]
## Device you want to apply for
Xiaomi Poco X2 (Phoenix)

Your device name and codename
Xiaomi Poco X2 (Phoenix)

## Device tree sources

```
https://github.com/jaymistry258/android_device_xiaomi_phoenix.git
https://github.com/jaymistry258/android_kernel_xiaomi_phoenix.git
https://github.com/jaymistry258/android_vendor_xiaomi_phoenix.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Poco_X2_Builds
```

## Other ROM's you maintain officially or unofficially
```
https://t.me/Poco_X2_Builds
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1-Month
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
jaymistry258
```

**Comment by rockstar5495** [comment]
Use proper trees your commit history is fully messed up seems like kanged trees. Fix your trees and then apply again.

**Comment by jaymistry258** [comment]
> Use proper trees your commit history is fully messed up seems like kanged trees. Fix your trees and then apply again.

Okay i will fix it by tomorrow

**Comment by rockstar5495** [comment]
Still not upto mark use proper ssh for bringup there are so many portals for same like gitpod, Google cloud console etc don't use GitHub web for these.

**Comment by jaymistry258** [comment]
> Still not upto mark use proper ssh for bringup there are so many portals for same like gitpod, Google cloud console etc don't use GitHub web for these.

Still not satisfied then i'm out i will manage it as a unofficially.

**Comment by rockstar5495** [comment]
They up to you. You did bringup in 3 different commits which can be done in single commit if you refer to other trees.
