### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ahmedhridoy371** [Octavi-Staging/maintainership#2]
## Device you want to apply for
```
Your device name and codename
Redmi Note 7/7s (Lavender)
```

## Device tree sources

```
https://github.com/ahmedhridoy371/Device_wip
https://github.com/ahmedhridoy371/nexus_kernel_xiaomi_lavender
https://github.com/ahmedhridoy371/Vendor_wip
```

## Link to the platform where you have released your unofficial build
```
(Not Yet)
```

## Other ROM's you maintain officially or unofficially
```
1: SuperiorOs Officially 
2: Xtended Os officially 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
8/9 Month
```

## SELinux status?
```
Enforcing
`

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
```
Your Telegram username
@Apex_Not_Legend

**Comment by rockstar5495** [comment]
You are accepted welcome to team change your privacy settings if any we will add soon and read Code of Conduct before joining group.

**Comment by ahmedhridoy371** [comment]
> You are accepted welcome to team change your privacy settings if any we will add soon and read Code of Conduct before joining group.

Thanks For Confirmation
