### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by NRanjan-17** [Octavi-Staging/maintainership#3]
## Device you want to apply for
```
Redmi Note 4/4X (mido)
```

## Device tree sources

https://github.com/NRanjan-17/device_xiaomi_mido/tree/Octavi-staging
https://github.com/NRanjan-17/kernel_xiaomi_mido 
https://github.com/NRanjan-17/vendor_xiaomi_mido 
```

## Link to the platform where you have released your unofficial build
```
Not Released yet
```

## Other ROM's you maintain officially or unofficially
```
Official PixelExperience and PixysOS 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 year
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
```
HyperPower17
```

**Comment by rockstar5495** [comment]
You are accepted and welcome to team.

**Comment by NRanjan-17** [comment]
Thank you
